name: RT-AK with plugin-example CI

on: [push, pull_request]

jobs:
  RT-AK-Github-Actions:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]  # only support ubuntu now

  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Install System Requirements(Linux)
    if: runners.os == 'Linux'
    shell: bash
    run: |
      echo "Prepared BSP"

  - name: Setup Python
    uses: actions/setup-python@v2.2.1
    with:
      python-version: 3.7
    
  - name: Install dependecies
    run: |
      python -m pip install --upgrade pip
      pip install scons
      scons -v


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true
        
    - name: download
      run : |
        pip install wget scons
        scons -v
        cd RT-AK/test
        python download_file.py
        ls ../tmp
        
        # run ai_tools.py
        cd ../rt_ai_tools
        python aitools.py --project="../tmp/sdk-bsp-artpi" --model='./Models/keras_mnist.h5' --platform='stm32' --ext_tools="../tmp/windows" --clear
        echo "Run RT-AK Tools done."
    
        # compiler
        cd ../tmp/sdk-bsp-artpi
        scons -j 6
        echo "Compiler done."